apiVersion: 1

contactPoints:
  - orgId: 1
    name: argus-default
    receivers:
      - uid: argus-log-receiver
        type: webhook
        settings:
          url: http://api:8000/health
          httpMethod: GET
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: argus-default
    group_by: ["alertname"]
    routes: []
